name: first Workflow

on:
  push:
    branches:
      - main
      - master


jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: print a welcome message
        run: echo "Welcome to the first workflow!"

      - name: Chackout reposotory
        uses: actions/checkout@v2
      
      - name: List reposotory files
        run: ls -la
          
